### ISSUE TITLE
глобальные переменные -- это очень плохо.

### ISSUE THREAD

**Issue by lariliel** [mmjax/code_for_school#12]
https://github.com/mmjax/code_for_school/blob/556c2ddf1c130a0678f2ea90c6ba22efe4b010f4/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%E2%84%961/computeFunctions.c#L9

**Comment by mmjax** [comment]
ужасные глобальные переменные были удалены и заменены на указатели
