### ISSUE TITLE
не компилица

### ISSUE THREAD

**Issue by lariliel** [mmjax/code_for_school#13]
gcc -DDEBUG -DMAX_N=5 -DMAX_M=5 -o calc -Wall -Wextra -Werror main.c
Undefined symbols for architecture x86_64:
  "_computeFunction", referenced from:
      _main in main-3d6d1b.o
  "_parseFunction", referenced from:
      _main in main-3d6d1b.o
  "_parseSet", referenced from:
      _main in main-3d6d1b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mmjax** [comment]
не компилилось т.к. в компилировалось только main.c, в моём проекте есть два файла связанные с header (на данный момент хедеры для связки двух файлов не используются, и код спокойно может компилица)
