### ISSUE TITLE
Поправь так будет легче

### ISSUE THREAD

**Issue by neolnoel** [mmjax/code_for_school#14]
https://github.com/mmjax/code_for_school/blob/0daf6bc06f48f31887f03ec995bb43045d55697f/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%E2%84%961/main.c#L1

для файла build.bat (убери там computeFunctions.с)

а это добавь в main.c
#include "computeFunctions.с"

**Comment by mmjax** [comment]
убрал ))))
