### ISSUE TITLE
Не очень понимаю,что делает этот else

### ISSUE THREAD

**Issue by RTgrave** [mmjax/code_for_school#16]
https://github.com/mmjax/code_for_school/blob/0daf6bc06f48f31887f03ec995bb43045d55697f/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%E2%84%961/computeFunctions.c#L128

**Comment by mmjax** [comment]
чтоб найти первый символ числа 'b' и с помощью функции "atoi" перевести в int число записанное на месте 'b'
