### ISSUE TITLE
Для чего это нужно?

### ISSUE THREAD

**Issue by LuckyMillioner** [mmjax/code_for_school#19]
https://github.com/mmjax/code_for_school/blob/1fbbcb359e81e9380b8c1e9e485f48f94e86c064/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%E2%84%961/build.bat#L1

**Comment by mmjax** [comment]
http://moria.1586.su/moodle/mod/page/view.php?id=1714
здесь всё объясняется
