### ISSUE TITLE
Просто я тупой.

### ISSUE THREAD

**Issue by neolnoel** [mmjax/code_for_school#20]
https://github.com/mmjax/code_for_school/blob/914d795d0e45a3ed66fe33f06f1d4ea5fe9af130/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%E2%84%961/test.bat#L1

зачем тебе полностью этот файл?

**Comment by mmjax** [comment]
я ответил на вопрос ЛИЧНО
